EXAMPLES/bsconfig.json, EXAMPLES/package.json, README.md, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/Jeddeloh__ApolloClient.re
Here are some proposed changes to the general shape of hooks. They follow the same pattern as client methods where variables are in the last position and required in order to improve type inference. This simplified things quite a bit.
The case where you have some variables but none are _required_ is still slightly awkward, but I think this is a better approach than having the variables arg be optional in that case. If you have optional variables and you're not supplying _any_ seems rare and I would rather someone have to be explicit that they are not passing anything rather than possibly forgetting.
=> Improve type inference by moving variables to last position in hooks

src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/client/link/http/ApolloClient__Link_Http_ParseAndCheckHttpResponse.re, src/@apollo/client/link/utils/ApolloClient__Link_Utils_ThrowServerError.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/@apollo/link-error/ApolloClient__LinkError.re
Apollo types the `networkError` property on `ApolloError` as `Error | null` which is kinda tragic. This is my initial exploration at fleshing things out. In an ideal world, network error would be something like this: https://github.com/elm/http/blob/2.0.0/src/Http.elm#L538
```
type Error
= BadUrl String
| Timeout
| NetworkError
| BadStatus Int
| BadBody String
```
Unfortunately we don't have much ability to get this information after the fact. The types in `@apollo/link-error` are better: `Error | ServerError | ServerParseError` So tried working with that. It's wasn't clear to me from those names what they actually mean without digging into the internals of Apollo. If I were to rename them I'd do something like this: 
```
type networkError =
| FetchFailure(Js.Exn.t)
| BadStatus(int, …
```
=> Flesh out network error

EXAMPLES/src/clientUsage/ClientBasics.re, src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.re, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/client/utilities/observables/ApolloClient__Utilities_Observables.re, src/@apollo/client/utilities/observables/ApolloClient__Utilities_Observables_Observable.re, src/Jeddeloh__ApolloClient.re, src/zen-observable/ApolloClient__ZenObservable.re
This adds support for the `watchQuery` method on `ApolloClient`. The bindings here were a little awkward made more difficult by a bug in Apollo Client 3 where you can't `.map` an `ObservableQuery`. I'm sure we can do better on another pass.
=> Add watchQuery

EXAMPLES/src/App.re, EXAMPLES/src/hooksUsage/Query_SubscribeToMore.re, EXAMPLES/src/hooksUsage/Query_Typical.re, EXAMPLES/src/hooksUsage/Subscription.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/Jeddeloh__ApolloClient.re
Here I was, thinking I was done, and I'd missed this huge swath of extended properties on QueryResult 😆.
This PR basically adds stuff like `fetchMore` and `subscribeToMore`. It's a bit tragic for a number of reasons:
- I have to mix and match direct access on the record for values, but have separate functions for methods on the same result object which can sometimes be a little confusing when things feel _so_ close to the javascript usage.
- Separating the methods from the result record means that I lose context of the operation that was used originally so now I  attach `parse` and `serialize` to the result record to be used in the method functions.
On the upside, I've attached them as abstract types and you'll get the following error when trying to use them:
```
This expression has type …
```
=> QueryResult methods

EXAMPLES/package.json, EXAMPLES/src/clientUsage/ClientBasics.re, EXAMPLES/src/hooksUsage/Mutation.re, EXAMPLES/src/hooksUsage/Query_SubscribeToMore.re, EXAMPLES/src/hooksUsage/Query_Typical.re, README.md, src/ReasonMLCommunity__ApolloClient.re
I took one more pass at the structure of the root module. The ideas is that the root attempts to present a clear structure for everything needed to create, configure, and query with a client. Then, if you have some result and want to call a method or need access to some type to annotate options, everything is available in the `Types` module.
You can see the effect in the examples.
=> Improved root module structure and easier types access

src/ReasonMLCommunity__ApolloClient.re, src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.re
Just fleshing out subscriptions transport a little more. Useful if you need to refresh subscriptions in flight with new connectionParams.
=> Close method for subscriptions-transport-ws

EXAMPLES/bsconfig.json, README.md
kebab-case still works but will be deprecated in `graphql-ppx` at some point.
=> use camelCase for configuration

src/@apollo/client/link/ws/ApolloClient__Link_Ws.re
When you're using `Link.WebSocket.makeWithSubscriptionClient` it's a bit hard to know where to get the subscription client without going through the `Bindings` path.
=> Expose SubscriptionClient from WebSocketLink

EXAMPLES/bsconfig.json, EXAMPLES/package.json, EXAMPLES/src/clientUsage/ClientBasics.re, EXAMPLES/src/hooksUsage/Query_Typical.re, bsconfig.json, package.json, src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.re, src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_DataProxy.re, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.re, src/@apollo/client/core/ApolloClient__Core_Types.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/client/link/context/ApolloClient__Link_Context.re, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re, src/@apollo/client/link/error/ApolloClient__Link_Error.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.re, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/ApolloClient__Types.re, src/ApolloClient__Utils.re, src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.re
This PR attempts to resolve the outstanding configuration needs: #22. It was originally thought some sort of configuration module and functors would be necessary, but with a few smart choices I think we can avoid it. I went down that path for a bit and we’d definitely like to avoid it!
As it currently stands, this experiment only covers `query` and `useQuery` and there are still some things I would like to change or clean up about the current implementation. That said, I'd like to get feedback on the approach before going much further.
We use records a lot, so using a T-first promise library for better type inference would be very helpful. There should also be a way to opt out or provide their own promise transformation function. Here I've chosen to use `reason-promise`, but how do we …
=> Results and Promises

EXAMPLES/package.json, EXAMPLES/src/clientUsage/ClientBasics.re, EXAMPLES/src/hooksUsage/Mutation.re, EXAMPLES/src/hooksUsage/Query_SubscribeToMore.re, EXAMPLES/src/hooksUsage/Query_Typical.re, src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.re, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.re, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies.re, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.re, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re, src/@apollo/client/link/core/ApolloClient__Link_Core_ApolloLink.re, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re, src/@apollo/client/link/error/ApolloClient__Link_Error.re, src/@apollo/client/link/ws/ApolloClient__Link_Ws.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/ReasonMLCommunity__ApolloClient.re, src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.re, src/zen-observable/ApolloClient__ZenObservable.re
So I think I was thinking about this all wrong. It's only unsafe to write _bindings_ to an object method when using records. So we need to use `bs.send` for the `Js_` bindings, but after that we have no such limitations. Here, the function on the reason record has a closure to the original `Js_` object and the method is called using a `bs.send` binding. With this pattern, I think we can move to a much better api where you can destructure methods like `fetchMore` directly on the query result, etc.
In the changes, you can see the unsubscribe method that used to fail when the Js bindings were written directly as a record, but this works perfectly fine.
=> Experiment with safe methods on records

EXAMPLES/src/clientUsage/ClientBasics.re, EXAMPLES/src/clientUsage/ClientMethodChaining.re, EXAMPLES/src/hooksUsage/Query_Typical.re, src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/core/ApolloClient__Core_Types.re, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/ApolloClient__Promise.re, src/ReasonMLCommunity__ApolloClient.re
In the last pass I converted all the async stuff to return a `Promise.t(someApolloResult)`, but I immediately realized it's very important that any async promise/monad have a way to bail out of a sequence of computation. So this PR finishes out how I would like promises to work by converting that `someApolloResult` into a proper `Belt.Result.t(nicerApolloResult, ApolloError.t)`. Take for example `FetchResult.t`:
```reason
module FetchResult = {
...
type t__ok('data) = {
data: 'data,
error: option(ApolloError.t),
extensions: option(Js.Json.t),
context: option(Js.Json.t),
};
let toResult: t('data) => Belt.Result.t(t__ok('data), ApolloError.t) =
fetchResult => {
switch (fetchResult) {
| {data: Some(data)} =>
Ok({
data,
error: fetchResult.error,
extensions: fetchResult.extensions,
context: …
```
=> Results Inception

src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re
`watchQuery` still had optional variables in the type which allows for the dreaded `Some(())` situation when you have no variables. Also I see I missed moving some variables serialization into the `toJs` functions.
=> serializeVariables

src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re
This fixes a binding that is totally incorrect because I was being lazy.
=> Remove unsafe binding in ApolloError.make

README.md, package.json, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/client/errors/__tests__/ApolloClient__Errors_ApolloError.test.js
`as Any`. Sadly, the types in Apollo Client can't be relied on totally and I've experienced `GraphQLerrors` sneaking into places where I'm destructuring an `ApolloError` when using subscriptions. I made a PR for the issue months back and even scaled it back to almost nothing, but no response: https://github.com/apollographql/apollo-client/pull/6894 Either I'm totally missing something or the team is swamped. 🤷 Anyway, we can deal with it here instead.
=> Extra ApolloError validation

src/@apollo/client/core/ApolloClient__Core_NetworkStatus.re
I'm using your next branch
I noticed there is no network status of 5.
https://github.com/apollographql/apollo-client/blob/main/docs/shared/query-result.mdx
A number from 1-8 (1 = loading, 2 = setVariables, 3 = fetchMore, 4 = refetch, 6 = poll, 7 = ready, 8 = error) corresponding to the detailed state of your network request. Includes information about refetching and polling status. Used in conjunction with the notifyOnNetworkStatusChange prop.
Thanks for your work
=> removed 5 from network status

src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.re
Missed parsing this completely somehow. These are not converting exceptions to result either. I'll do that in a next PR because I want to think about what shape it should take. `Some(Ok(data))`? Not super great.
=> Parse readFragment result

package.json, src/@apollo/client/ApolloClient__ApolloClient.re, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.re, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re, src/@apollo/client/react/types/ApolloClient__React_Types.re, src/ApolloClient__Types.re, src/ApolloClient__Utils.re
At some point, I wanted to statically differentiate between a parse result and some other sort of result to help with some conversions and I guess I just forgot to do the last step. Anyway, there are few places where the `parseResult` variant is exposed. This switches to regular results.
Also, the `readFragment` and `readQuery` methods were still throwing exceptions from parse. This fixes that so they now return an optional result.
=> Cache parse result

package.json, src/@apollo/client/react/types/ApolloClient__React_Types.res
- Resolves #83 
- Bumps minimum `@apollo/client` dependency to 3.3.0
`previousData` has a type of `option<result<'data, parseResult>>`. We're able to avoid the result on the normal `data` property by returning `None` on data and elevating a parse error to the `error` property of `QueryResult.t`, however I thought it would be confusing to do the same for `previousData`
=> previousData prop on QueryResult as of 3.3.0

EXAMPLES/package.json, src/@apollo/client/ApolloClient__Client.res, src/@apollo/client/core/ApolloClient__Core.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.res, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.res, src/@apollo/client/link/core/ApolloClient__Link_Core_ApolloLink.res, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.res, src/@apollo/client/link/error/ApolloClient__Link_Error.res, src/@apollo/client/react/context/ApolloClient__React_Context_ApolloProvider.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseApolloClient.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.res, src/@apollo/client/react/types/ApolloClient__React_Types.res, src/ApolloClient__Utils.res, src/ReasonMLCommunity__ApolloClient.res, src/zen-observable/ApolloClient__ZenObservable.res
It's always hard to strike the right balance of having accurate types in reason when many of these types are reused in typescript with `any`, like the `Observable` type in `ZenObservable`. I cheated a bit here and chose to just say that observables returned by apollo links always error with `Js.Exn.t`. We may need to revisit this.
=> Add subscribe method to ApolloClient.t

src/@apollo/client/link/core/ApolloClient__Link_Core_Types.res, src/zen-observable/ApolloClient__ZenObservable.res
Need to adjust NextLink types to account for the fact that zen-observable `Js_.t` and `t` types are different now.
=> NextLink types

documentationWebsite/docusaurus.config.js
For example this is broken: https://github.com/reasonml-community/rescript-apollo-client/edit/master/documentation/docs/client-configuration.md
=> Fix incorrect/broken link to edit docs from website

documentationWebsite/docs/client-configuration.md
This code doesn't actually compile as is, it is looking for a `UriFunction.t`. I'm not sure if this is an error and should be changed to just a string. The docs don't mention any function.
(currently my code has `~uri="somelink"->Obj.magic` and it is working)
=> Add missing comma from docs

bsconfig.json, package.json
Looks like having `reason-react` in deps is causing problems when using with `rescript`.
See https://github.com/rescript-lang/rescript-react/issues/6#issuecomment-778343804
This fixed it in a patch for me. Once its updated you would have to update the import in the example.
=> @rescript/react@0.10.1

.npmignore, EXAMPLES/bsconfig.json, EXAMPLES/package.json, EXAMPLES/src/WebpackEntry.res, package.json
This branch is available via `rescript-apollo-client@next`. The only change is updating the `reason-react` dependency to `@rescript/react`. My plan was to wait for a proper release until any documentation (migration or otherwise) is up for it.
=> Next (@rescript/react)

src/@apollo/client/link/error/ApolloClient__Link_Error.res
https://github.com/jeddeloh/rescript-apollo-client/issues/116
Fixed an issue where objects could not be found due to unnecessary currying.
You can now properly use the forward function in ErrorLink 
```res
let errorLink: ApolloClient.Link.t = ApolloClient.Link.ErrorLink.make(handler => {
// Todo forward, operation 처리
let {networkError, graphQLErrors, operation, response, forward} = handler
switch graphQLErrors {
| Some(e') => e'->Array.map(v => v->handleGraphQLError)
| None => [()]
}->ignore
switch networkError {
| Some(networkError') => handleNetworkError(networkError')
| None => ()
}->ignore
switch response {
| Some(response') => Js.log2("Error Link response", response')
| None => ()
}->ignore
let dict = Js.Dict.empty()
let headers = Js.Dict.empty()
headers->Js.Dict.set( …
```
=> fix: uncurried invoke

src/@apollo/client/ApolloClient__Client.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/testing/ApolloClient__MockedProvider.res, src/@apollo/client/testing/ApolloClient__Testing.res, src/@apollo/client/testing/ApolloClient__Testing_Types.res, src/@apollo/client/testing/core/ApolloClient__Testing_Core.res, src/@apollo/client/testing/react/ApolloClient__Testing_React.res, src/@apollo/client/testing/react/ApolloClient__Testing_React_MockedProvider.res, src/ReasonMLCommunity__ApolloClient.res
Create `<MockedProvider />` in rescript.
- We need to create the apollo client in rescript so that methods like `rescript_query` that are added to the client instance are available. 
- We need to serialize the data back to `Js.Json.t` so that we are writing to the apollo cache since cannot write variants to the cache.
- Apollo differentiates `null` and `undefined` when writing to the cache. `None` translates to `undefined`
- Expose `makeResult` method that takes in `toJson` method that knows how to serialize back to `Js.Json.t`. That method is generated as a part of the graphql ppx
=> Bind mocked provider

src/@apollo/client/react/types/ApolloClient__React_Types.res
=> Fix options creation for @apollo/client >= 3.5

EXAMPLES/package.json, EXAMPLES/src/hooksUsage/Query_SubscribeToMore.res, src/graphql/language/ApolloClient__Graphql_Language_Ast.res
Also a little cleanup:
- fix type issue in examples
- Upgrade apollo client in examples
=> Account for missing name on OperationDefinitionNode

src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.res
I feel like this is pretty close. Something's wrong with the `@unboxed` though:
```ocaml
open ApolloClient
make(
~cache=Cache.InMemoryCache.make(
~typePolicies=[
(
"Trip",
Cache.InMemoryCache.TypePolicy.make(
~fields=[
(
"elements",
FieldPolicy({
merge: Some(MergeFunction(incomingMerge)),
read: None,
keyArgs: None,
}),
),
],
(),
),
),
```
Compiles to
```javascript
ApolloClient.make(undefined, undefined, undefined, Caml_option.some(httpLink), ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, [
[
"Trip",
ApolloClient__Cache_InMemory_Policies.TypePolicy.make([[
"elements",
{
TAG: /* FieldPolicy */3,
_0: {
keyArgs: undefined,
read: undefined,
merge: /* MergeFunction */{
_0: incomingMerge
}
}
}
]], undefined, undefined, undefined, undefined, undefined) …
```
=> Implement FieldMerge and FieldMergeFunction

.gitattributes, .gitignore, EXAMPLES/bsconfig.json, EXAMPLES/package.json, bsconfig.json, package.json, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.res, src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_DataProxy.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.res, src/@apollo/client/core/ApolloClient__Core_Types.res, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.res, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.res, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.res, src/@apollo/client/link/http/ApolloClient__Link_Http_HttpLink.res, src/@apollo/client/link/http/ApolloClient__Link_Http_SelectHttpOptionsAndBody.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_DelayFunction.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_RetryFunction.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_RetryLink.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.res, src/@apollo/client/react/types/ApolloClient__React_Types.res, src/@apollo/client/utilities/policies/ApolloClient__Utilities_Policies_Pagination.res, src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.res
Resolves #151
**BREAKING**: Requires optional record fields support from `rescript@^10.0.0`
**Potentially disruptive** (but hopefully not): Drops peer-dependency for `bs-platform`. It seems pretty likely that most people would be moved to at least `rescript@9` (which was just a re-name) or `melange` by this point.
=> BREAKING: convert @obj and @deriving(abstract) to use optional record fields

EXAMPLES/bsconfig.json, EXAMPLES/package.json, EXAMPLES/src/Apollo.res, EXAMPLES/src/WebpackEntry.res, bsconfig.json, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies.res, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.res, src/@apollo/client/core/ApolloClient__Core_Types.res, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.res, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.res, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.res, src/@apollo/client/link/error/ApolloClient__Link_Error.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_DelayFunction.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_RetryFunction.res, src/@apollo/client/link/retry/ApolloClient__Link_Retry_RetryLink.res, src/@apollo/client/link/ws/ApolloClient__Link_Ws.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseLazyQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.res, src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.res, src/@apollo/client/react/types/ApolloClient__React_Types.res, src/@apollo/client/utilities/policies/ApolloClient__Utilities_Policies_Pagination.res, src/ApolloClient__Types.res, src/ApolloClient__Utils.res, src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.res
Changes the internal usage of most externals or function definitions used at runtime to be explicitly uncurried functions. The intent here is that the `Js_` modules are changed, not the public API. This will eliminate any ambiguous function calling conventions when the consumer of this library is on ReScript v10 or v11 on curried mode.
=> Uncurries internals for rescript 11 compatibility
