CODE_OF_CONDUCT.md, CONTRIBUTING.md, EXAMPLES/README.md, EXAMPLES/graphql_schema.json, EXAMPLES/package.json, EXAMPLES/src/App.re, EXAMPLES/src/Client.re, EXAMPLES/src/clientUsage/ClientBasics.re, EXAMPLES/src/hooksUsage/Mutation.re, EXAMPLES/src/hooksUsage/Query_Lazy.re, EXAMPLES/src/hooksUsage/Query_OverlySimple.re, EXAMPLES/src/hooksUsage/Query_Typical.re
This is a quick pass at using a lightweight graphql server since the current one is going to die soon (idea proposed in reason-apollo-hooks, actually). It also tries to avoid some issues with people running the examples.
=> Example server

EXAMPLES/src/clientUsage/ClientBasics.re, src/@apollo/client/core/ApolloClient__Core_ObservableQuery.re, src/zen-observable/ApolloClient__ZenObservable.re
Totally forgot to finish the the observable subscription bindings in last PR 😅
=> Add unsubscribe method for Observable Subscription

src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/link-error/ApolloClient__LinkError.re
Two people voting is enough for quorum I guess :) This already feels much better.
=> Better networkError variants

EXAMPLES/src/hooksUsage/Query_Typical.re, src/@apollo/client/react/types/ApolloClient__React_Types.re
There was an issue with passing {query: undefined} to fetchMore, but it was also mostly wrong 🤦
=> Revisit fetchMore

src/@apollo/client/link/core/ApolloClient__Link_Core_ApolloLink.re, src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re, src/ReasonMLCommunity__ApolloClient.re
Just improving the types here a bit.
=> A more reasonable ApolloLink.make

EXAMPLES/src/Client.re, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.re
Misread `Extract<FetchPolicy, 'no-cache'>`
=> Update mutation fetch policy

src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re
=> FetchResult has errors of array(GraphqlError.t)

EXAMPLES/package.json, EXAMPLES/src/caching/LocalStateManagement.re, package.json, src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types.re, src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_Common.re, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies.re, src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.re, src/@apollo/client/utilities/ApolloClient__Utilities.re, src/@apollo/client/utilities/graphql/ApolloClient__Utilities_Graphql.re, src/@apollo/client/utilities/graphql/ApolloClient__Utilities_Graphql_StoreUtils.re, src/@apollo/client/utilities/policies/ApolloClient__Utilities_Policies_Pagination.re
Pretty lame effort here, but should get the job done.
=> Fleshing out FieldReadFunction

src/@apollo/client/link/core/ApolloClient__Link_Core_Types.re, src/@apollo/client/link/error/ApolloClient__Link_Error.re
I'm sure there are a couple more methods that I missed when writing the original bindings.
=> Preserve Js Operation methods

EXAMPLES/package.json, README.md, package.json, src/@apollo/client/errors/ApolloClient__Errors_ApolloError.re, src/@apollo/client/errors/__tests__/ApolloClient__Errors_ApolloError.test.js, src/graphql/error/ApolloClient__Graphql_Error_GraphQLError.re, src/graphql/language/ApolloClient__Graphql_Language_Ast.re, src/graphql/language/ApolloClient__Graphql_Language_Source.re
=> GraphQLError properties

src/@apollo/client/core/ApolloClient__Core_NetworkStatus.re
=> Add SkippedOrNotPresent NetworkStatus variant

src/@apollo/client/errors/ApolloClient__Errors_ApolloError.res
=> Fix bug in ensureApolloError

.npmignore, package.json
- Allows bs-platform 9
- docs/ directory snuck into npm package
=> Bs platform 9 & npm package cleanup

documentationWebsite/docs/installation.md
I had been caught by the instruction and this make me unable to build.
Discussed about that with @jfrolich, who maintain graphqlppx, that's how it should be :)
=> Fix installation instruction part about templateTagIsFunction

src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.res
FYI: 
https://www.apollographql.com/docs/react/api/core/ApolloClient/#ApolloClient.watchQuery
=> Add nextFetchPolicy to watchQuery options

src/@apollo/client/core/ApolloClient__Core_ApolloClient.res
Add extract method to apollo client.
https://github.com/apollographql/apollo-client/blob/d3a74ec87cee2b9819a7bb5f2be605c14857aa28/src/core/ApolloClient.ts#L592
=> feat: add apollo.extract method

EXAMPLES/src/clientUsage/ClientBasics.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/core/ApolloClient__Core_WatchQueryOptions.res
=> Add pollInterval option to ApolloClient.watchQuery

package.json, src/@apollo/client/cache/core/ApolloClient__Cache_Core_Cache.res, src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_DataProxy.res, src/@apollo/client/core/ApolloClient__Core_ApolloClient.res, src/@apollo/client/react/types/ApolloClient__React_Types.res
=> @apollo/client 3.5 features

EXAMPLES/bsconfig.json, EXAMPLES/package.json, EXAMPLES/src/WebpackEntry.res, EXAMPLES/src/clientUsage/AsyncAwait.res, EXAMPLES/src/clientUsage/ClientBasics.res, EXAMPLES/src/docs/Docs.res, EXAMPLES/src/fragmentsUsage/Query_Fragments.res, EXAMPLES/src/hooksUsage/Mutation.res, EXAMPLES/src/hooksUsage/Query_Lazy.res, EXAMPLES/src/hooksUsage/Query_OverlySimple.res, EXAMPLES/src/hooksUsage/Query_Typical.res, EXAMPLES/webpack.config.js, bsconfig.json, package.json
This should be all backwards compatible
I updated the `EXAMPLES` project with the latest stuff as well.
=> Rescript 10.1

src/@apollo/client/react/types/ApolloClient__React_Types.res
=> fix: LazyQueryResult.Js_.classify was checking the wrong value

src/@apollo/client/core/ApolloClient__Core_ApolloClient.res
=> fix: infinite loop when calling stop
